name: animation
description: Showcasing how to drive animations with state_beacon
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    state_beacon:
        path: ../../packages/state_beacon

dependency_overrides:
  state_beacon_core: 
    path: ../../packages/state_beacon_core
  state_beacon_flutter: 
    path: ../../packages/state_beacon_flutter
    
dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
